### ISSUE TITLE
So does this work on getting the right answers in a google form?

### ISSUE THREAD

**Issue by peakmouse** [Chamepp/GoogleForms#1]

**Comment by Chamepp** [comment]
Infact this tool is still in demo and the building is passing by ...
But you're able to use the rapid option for make tool to take actions by
credentials you give about the target google form.
The secret finder attack further which is for getting right answers will be
available soon for v1 release. The Rapid Attack Option is already available.
Will appreciate your support by a 🌟 on repo.

Thanks and Regards.
