### ISSUE TITLE
installing requirements thru windows cmd

### ISSUE THREAD

**Issue by ClainRaniel** [Chamepp/GoogleForms#19]
C:\Users\user\Desktop\GoogleForms-master\App>pip3 install -r requirements.txt
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Requirement already satisfied: selenium in c:\python39\lib\site-packages (from -r requirements.txt (line 1)) (3.141.0)
Requirement already satisfied: beautifulsoup4 in c:\python39\lib\site-packages (from -r requirements.txt (line 2)) (4.9.3)
Collecting string-color
  Using cached string_color-1.2.1-py3-none-any.whl (13 kB)
Collecting prompt_toolkit==1.0.14
  Using cached prompt_toolkit-1.0.14-py3-none-any.whl (248 kB)
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-py05rpni\\selectmenu_a8c1d0a4a87048d4be5b01b5d906c32c\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-py05rpni\\selectmenu_a8c1d0a4a87048d4be5b01b5d906c32c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\clain\AppData\Local\Temp\pip-pip-egg-info-4dxar5pr'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_a8c1d0a4a87048d4be5b01b5d906c32c\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_a8c1d0a4a87048d4be5b01b5d906c32c\setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_a8c1d0a4a87048d4be5b01b5d906c32c\selectmenu\__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_a8c1d0a4a87048d4be5b01b5d906c32c\selectmenu\core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (C:\Python39\lib\site-packages\prompt_toolkit\token.py)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cd/b9/8078a7f34c5b877e7fa26e5c5c5f62cbc765d44c949dd672a29aef62089a/SelectMenu-1.0.0b2.tar.gz#sha256=9e8623a5ac1a632b5f1e7a96698d62f7e76a4307639e4d7433e8a1a28c263e73 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached SelectMenu-1.0.0b1.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-py05rpni\\selectmenu_fe29228a28fc4b589e84b84f68493bed\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-py05rpni\\selectmenu_fe29228a28fc4b589e84b84f68493bed\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\clain\AppData\Local\Temp\pip-pip-egg-info-po9mn16j'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_fe29228a28fc4b589e84b84f68493bed\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_fe29228a28fc4b589e84b84f68493bed\setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "C:\Users\user\AppData\Local\Temp\pip-install-py05rpni\selectmenu_fe29228a28fc4b589e84b84f68493bed\selectmenu\__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "C:\Users\clain\AppData\Local\Temp\pip-install-py05rpni\selectmenu_fe29228a28fc4b589e84b84f68493bed\selectmenu\core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (C:\Python39\lib\site-packages\prompt_toolkit\token.py)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/9d/0692d5996b163b8d5eba7b3743b70e9f2da513d818ddde1a4f9573340341/SelectMenu-1.0.0b1.tar.gz#sha256=6da29a48da916b2e794e92c689fb6c264205a9886d41fb35d1aac0533de9ee62 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement SelectMenu (from versions: 1.0.0b1, 1.0.0b2)
ERROR: No matching distribution found for SelectMenu
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)

**Comment by chanraakternasan** [comment]
(sorry for my broken english) I think you cannot use this project on CMD on Windows because the 'SelectMenu' module **IS SEEMS UNAVAILABLE FOR WINDOWS**. You should try to use Ubuntu in the Microsoft store and compile it again
![image](https://user-images.githubusercontent.com/78898421/133731547-fba836ee-352f-4948-b76b-dc35de2889cd.png)

**Comment by chanraakternasan** [comment]
(sorry for my broken english)Can you try it in Ubuntu for Windows? Because I can do it without any problem 
![image](https://user-images.githubusercontent.com/78898421/133732263-2803b002-62c0-412d-a8cf-797b3e25e3ce.png)

**Comment by ClainRaniel** [comment]
/Desktop/GoogleForms-master/App$ python3 -m pip install -r requirements.txt
Collecting selenium
  Downloading selenium-4.0.0-py3-none-any.whl (954 kB)
     |████████████████████████████████| 954 kB 2.4 MB/s
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 3.1 MB/s
Collecting string-color
  Downloading string_color-1.2.1-py3-none-any.whl (13 kB)
Collecting prompt_toolkit==1.0.14
  Downloading prompt_toolkit-1.0.14-py3-none-any.whl (248 kB)
     |████████████████████████████████| 248 kB 5.8 MB/s
Collecting SelectMenu
  Downloading SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gcpa2345/SelectMenu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gcpa2345/SelectMenu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-gcpa2345/SelectMenu/pip-egg-info
         cwd: /tmp/pip-install-gcpa2345/SelectMenu/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gcpa2345/SelectMenu/setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "/tmp/pip-install-gcpa2345/SelectMenu/selectmenu/__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "/tmp/pip-install-gcpa2345/SelectMenu/selectmenu/core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ModuleNotFoundError: No module named 'prompt_toolkit'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Desktop/GoogleForms-master/App$ python3 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from sty import fg, bg, ef
ModuleNotFoundError: No module named 'sty'
Desktop/GoogleForms-master/App$ pip install SelectMen
ERROR: Could not find a version that satisfies the requirement SelectMen (from versions: none)
ERROR: No matching distribution found for SelectMen
/Desktop/GoogleForms-master/App$ pip install SelectMenu
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-p0ol5u6d/SelectMenu/setup.py'"'"'; __file__='"'"'/tmp/pip-install-p0ol5u6d/SelectMenu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-p0ol5u6d/SelectMenu/pip-egg-info
         cwd: /tmp/pip-install-p0ol5u6d/SelectMenu/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p0ol5u6d/SelectMenu/setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "/tmp/pip-install-p0ol5u6d/SelectMenu/selectmenu/__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "/tmp/pip-install-p0ol5u6d/SelectMenu/selectmenu/core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ModuleNotFoundError: No module named 'prompt_toolkit'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by chanraakternasan** [comment]
Maybe try **pip uninstall prompt_toolkit==1.0.14** and then **pip install prompt_toolkit==1.0.14**?   Or **sudo apt-get remove prompt_toolkit==1.0.14** then **sudo apt-get install prompt_toolkit==1.0.14**
