### ISSUE TITLE
How do you use the program?

### ISSUE THREAD

**Issue by vlqdd** [Chamepp/GoogleForms#2]
Hey there! I am new in Github but i have a bit of knowledge in coding. Although i have a question. How do i use your program? and how can i run your program? i tried running it directly into cmd but i don't know what file to run. If you could please explain i would be really thankful. Thank you in advance!

**Comment by Chamepp** [comment]
Hey !
Happy to hear from you ...
For using it you should get some tools installed, the first one is git
which is for control versioning and repo management.

You should search google of how to clone repos in your desktop. Next thing
is python which is a programming language that used to write this tool with
it. After installing python you are able to run python files (.py).

Last things last, simply enter my tool directory and run the main file with
python.
The command below will do that:
python3 main.py

The tool is ready to use and you should define the XPath of the elements of
google forms webpage.
For that simply enter the form you want as target and do F12 and use google
debug console. You can search youtube about how to find XPath and
understand more about web element concepts.(More Clear Instructions, and
briefer ;) and one more thing is that the tool is passing by demo build and
its in beta with option one available. Will build the answer finder soon.

Maybe this seems frustrating but its just three steps. Entering any field
is a bit complicated for the reason getting to know environment, it will be
fine after two months (programming is easy).

Wish you the best on your way and welcome to this beautiful world and never
give up on this.
If you mind will appreciate your help by a 🌟 on my repo.

Regards,
Chamepp
(Hoof that was long ! Lol)

**Comment by vlqdd** [comment]
Thank you very much! I followed those 3 steps and it launched! As you said programming is easy and i find it really fun! I will definitely give you a 🌟 on your repo! I only have one more question. When i tried selecting the option 1 it said unidentified google drive path. And with that being said i think answer finder can't be used for now. I believe that is because the tool as you said is in demo build. I hope it will be fully released soon! I can't wait for the full release! Lots of thanks and good luck developing it further! Cheers!!

**Comment by Chamepp** [comment]
Oh sorry, forgot to say,
Just simply download google driver and give the installation path to the
program.
Thanks for the 🌟.

Regards,
Chamepp

**Comment by Webbers-Dev** [comment]
Hey im really confuse you say "simply enter my tool directory and run the main file with
python." can i know which one is the main file that i should run in python thank you

**Comment by Chamepp** [comment]
Go to venv/GoogleForms
and run main.py

**Comment by Webbers-Dev** [comment]
Oke thanks for your reply one last thing can i know what is "download google driver and give the instalation path to the program" mean?
