### ISSUE TITLE
No module named 'html.parser'; 'html' is not a module

### ISSUE THREAD

**Issue by Pogikosobra** [Chamepp/GoogleForms#21]
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
Collecting string-color
  Using cached string_color-1.2.1-py3-none-any.whl (13 kB)
Collecting prompt_toolkit==1.0.14
  Using cached prompt_toolkit-1.0.14-py3-none-any.whl (248 kB)
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
Collecting sty
  Using cached sty-1.0.0rc2-py3-none-any.whl (11 kB)
Collecting html
  Using cached html-1.16.tar.gz (7.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ba7fa1nj/html/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ba7fa1nj/html/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ba7fa1nj/html/pip-egg-info
         cwd: /tmp/pip-install-ba7fa1nj/html/
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 35, in <module>
        from setuptools.depends import Require
      File "/usr/lib/python3/dist-packages/setuptools/depends.py", line 6, in <module>
        from .py33compat import Bytecode
      File "/usr/lib/python3/dist-packages/setuptools/py33compat.py", line 11, in <module>
        from setuptools.extern.six.moves import html_parser
      File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 92, in __get__
        result = self._resolve()
      File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 115, in _resolve
        return _import_module(self.mod)
      File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 82, in _import_module
        __import__(name)
    ModuleNotFoundError: No module named 'html.parser'; 'html' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by NDiMC** [comment]
I'm using with wsl.exe (Ubuntu but in Windows 10), and I just remove "html" from 'requirements.txt' ( just like in my screenshot ). Then, run again the code setup 'pip3 install -r requirements.txt' in wsl.exe, after that 'requirement' will be satisfied. ( Sorry for my bad English, because English is my 2nd language :' )

![Screenshot 2021-10-15 183605](https://user-images.githubusercontent.com/92581474/137481806-f274a3ff-a639-4717-8b38-af0e775369ac.png)
