### ISSUE TITLE
Wont work : /

### ISSUE THREAD

**Issue by emraldmty** [Chamepp/GoogleForms#25]
Hi for some reason when I enter my chrome driver location, it doesn't work but when i try to find the driver, I can't find [it](url)
![Plz help](https://user-images.githubusercontent.com/99238571/152927154-9afd6654-47de-4340-a7ca-305576c0b14a.PNG)

**Comment by Chamepp** [comment]
Hi emraldmty,
the error describes wrong path of chrome driver, make sure to have the same version of chrome driver and chrome
