### ISSUE TITLE
When will this program fully work?

### ISSUE THREAD

**Issue by ScientistAlif** [Chamepp/GoogleForms#5]
Hi Chamepp,
I had already installed all the requirements and had it launched. However, I found that the secret finder feature wouldn't run maybe because you haven't developed it yet. So, when will the secret finder work? And could you tell us in advance on how to run the feature?

Thank you.
Regards, 
Alif

**Comment by Chamepp** [comment]
Hello Alif,
Im completing the base of app and rapid input and environment skeleton is already done.
secret finder will get developed soon
