### ISSUE TITLE
Downloading requirements

### ISSUE THREAD

**Issue by FancyWaifu** [Chamepp/GoogleForms#6]
----@---- App % python3 main.py        
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from selectmenu import SelectMenu
ModuleNotFoundError: No module named 'selectmenu'
---@--- App % pip3 install selectmenu
Collecting selectmenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-install-yfidxkih/selectmenu/setup.py'"'"'; __file__='"'"'/private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-install-yfidxkih/selectmenu/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-pip-egg-info-_fv7c7um
         cwd: /private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-install-yfidxkih/selectmenu/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-install-yfidxkih/selectmenu/setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "/private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-install-yfidxkih/selectmenu/selectmenu/__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "/private/var/folders/xs/6pgnzt190rdd2xsk_sgv9p_r0000gn/T/pip-install-yfidxkih/selectmenu/selectmenu/core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ModuleNotFoundError: No module named 'prompt_toolkit'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.

**Comment by Chamepp** [comment]
Enter App Directory ...
pip3 install -r requirements.txt
