### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by laurencebedford** [Chamepp/GoogleForms#7]
Hey,

First thing it says is I can only use rapid attack, secondly where do I import the link etc?

**Comment by laurencebedford** [comment]
usertarget = input("\nEnter Your Target [1 TO {max}] : ".format(max = convertcount))
UnboundLocalError: local variable 'convertcount' referenced before assignment

**Comment by Chamepp** [comment]
you should just give the direct link to tool.
like this one https://docs.google.com/forms/d/e/1FAIpQLSfYIQfEm3Q08Weosbu44Qc72wzWW1vC-Voy4j3AflHTUXFqtQ/viewform
the error in your second comment is for not inserting any link value

**Comment by laurencebedford** [comment]
> you should just give the direct link to tool.
> like this one https://docs.google.com/forms/d/e/1FAIpQLSfYIQfEm3Q08Weosbu44Qc72wzWW1vC-Voy4j3AflHTUXFqtQ/viewform
> the error in your second comment is for not inserting any link value

Oh that explains, but how can I use the answer feature?? It just closes every time I select option 2?
