### ISSUE TITLE
pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by rip1aesthetics** [Chamepp/GoogleForms#8]
Requirement already satisfied: selenium in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.0.0a1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.9.3)
Collecting string-color
  Using cached string_color-1.2.1-py3-none-any.whl (13 kB)
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nm43kor8/selectmenu_f03b4b69814a4ee7baae23f8c7e69c5f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nm43kor8/selectmenu_f03b4b69814a4ee7baae23f8c7e69c5f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tknti70_                   
         cwd: /tmp/pip-install-nm43kor8/selectmenu_f03b4b69814a4ee7baae23f8c7e69c5f/                                                                                   
    Complete output (9 lines):                                                                                                                                         
    Traceback (most recent call last):                                                                                                                                 
      File "<string>", line 1, in <module>                                                                                                                             
      File "/tmp/pip-install-nm43kor8/selectmenu_f03b4b69814a4ee7baae23f8c7e69c5f/setup.py", line 5, in <module>                                                       
        from selectmenu import __author__, __version__                                                                                                                 
      File "/tmp/pip-install-nm43kor8/selectmenu_f03b4b69814a4ee7baae23f8c7e69c5f/selectmenu/__init__.py", line 4, in <module>                                         
        from selectmenu.core import SelectMenu                                                                                                                         
      File "/tmp/pip-install-nm43kor8/selectmenu_f03b4b69814a4ee7baae23f8c7e69c5f/selectmenu/core.py", line 6, in <module>                                             
        from prompt_toolkit.token import Token                                                                                                                         
    ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/usr/lib/python3/dist-packages/prompt_toolkit/token.py)                                       
    ----------------------------------------                                                                                                                           
WARNING: Discarding https://files.pythonhosted.org/packages/cd/b9/8078a7f34c5b877e7fa26e5c5c5f62cbc765d44c949dd672a29aef62089a/SelectMenu-1.0.0b2.tar.gz#sha256=9e8623a5ac1a632b5f1e7a96698d62f7e76a4307639e4d7433e8a1a28c263e73 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                                                
  Using cached SelectMenu-1.0.0b1.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nm43kor8/selectmenu_72410394ac054a328dc826b05940aba6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nm43kor8/selectmenu_72410394ac054a328dc826b05940aba6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nlc47vbm                   
         cwd: /tmp/pip-install-nm43kor8/selectmenu_72410394ac054a328dc826b05940aba6/                                                                                   
    Complete output (9 lines):                                                                                                                                         
    Traceback (most recent call last):                                                                                                                                 
      File "<string>", line 1, in <module>                                                                                                                             
      File "/tmp/pip-install-nm43kor8/selectmenu_72410394ac054a328dc826b05940aba6/setup.py", line 5, in <module>                                                       
        from selectmenu import __author__, __version__                                                                                                                 
      File "/tmp/pip-install-nm43kor8/selectmenu_72410394ac054a328dc826b05940aba6/selectmenu/__init__.py", line 4, in <module>                                         
        from selectmenu.core import SelectMenu                                                                                                                         
      File "/tmp/pip-install-nm43kor8/selectmenu_72410394ac054a328dc826b05940aba6/selectmenu/core.py", line 6, in <module>                                             
        from prompt_toolkit.token import Token                                                                                                                         
    ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/usr/lib/python3/dist-packages/prompt_toolkit/token.py)                                       
    ----------------------------------------                                                                                                                           
WARNING: Discarding https://files.pythonhosted.org/packages/a1/9d/0692d5996b163b8d5eba7b3743b70e9f2da513d818ddde1a4f9573340341/SelectMenu-1.0.0b1.tar.gz#sha256=6da29a48da916b2e794e92c689fb6c264205a9886d41fb35d1aac0533de9ee62 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                                                                                                                                
ERROR: Could not find a version that satisfies the requirement SelectMenu
ERROR: No matching distribution found for SelectMenu

I put pip3 install -r requirements.txt and I get that error, Any solution?

**Comment by Yuvraj15101999** [comment]
May be first try to use containers or virtual environment for the project, so that if anything goes wrong it might not affect the system, since there have been cases where keyloggers have being installed while installing some random scripts. And then have try it will work properly

**Comment by TAnvilrock** [comment]
Could you please elaborate more on how the solution works? Because I am also addicted to this problem.

**Comment by Chamepp** [comment]
Please check your python version.
this tool is passing build in python 3.8 with required packages.

**Comment by DevJohann** [comment]
When i do 'pip3 install -r requirements.txt' 

Requirement already satisfied: selenium in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (4.0.0a1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.9.3)
Collecting string-color
  Using cached string_color-1.2.1-py3-none-any.whl (13 kB)
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z15cw9is/selectmenu_21597f2d794347279c7e1a6c43a628b6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z15cw9is/selectmenu_21597f2d794347279c7e1a6c43a628b6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ynnkiyup                                                                
         cwd: /tmp/pip-install-z15cw9is/selectmenu_21597f2d794347279c7e1a6c43a628b6/                                                                        
    Complete output (9 lines):                                                
    Traceback (most recent call last):                                        
      File "<string>", line 1, in <module>                                    
      File "/tmp/pip-install-z15cw9is/selectmenu_21597f2d794347279c7e1a6c43a628b6/setup.py", line 5, in <module>                                            
        from selectmenu import __author__, __version__                        
      File "/tmp/pip-install-z15cw9is/selectmenu_21597f2d794347279c7e1a6c43a628b6/selectmenu/__init__.py", line 4, in <module>                              
        from selectmenu.core import SelectMenu                                
      File "/tmp/pip-install-z15cw9is/selectmenu_21597f2d794347279c7e1a6c43a628b6/selectmenu/core.py", line 6, in <module>                                  
        from prompt_toolkit.token import Token                                
    ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/usr/lib/python3/dist-packages/prompt_toolkit/token.py)                            
    ----------------------------------------                                  
WARNING: Discarding https://files.pythonhosted.org/packages/cd/b9/8078a7f34c5b877e7fa26e5c5c5f62cbc765d44c949dd672a29aef62089a/SelectMenu-1.0.0b2.tar.gz#sha256=9e8623a5ac1a632b5f1e7a96698d62f7e76a4307639e4d7433e8a1a28c263e73 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                 
  Using cached SelectMenu-1.0.0b1.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z15cw9is/selectmenu_4c361d97c5a1477bbeb17bfbf4f2ae73/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z15cw9is/selectmenu_4c361d97c5a1477bbeb17bfbf4f2ae73/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-19emy3rt                                                                
         cwd: /tmp/pip-install-z15cw9is/selectmenu_4c361d97c5a1477bbeb17bfbf4f2ae73/                                                                        
    Complete output (9 lines):                                                
    Traceback (most recent call last):                                        
      File "<string>", line 1, in <module>                                    
      File "/tmp/pip-install-z15cw9is/selectmenu_4c361d97c5a1477bbeb17bfbf4f2ae73/setup.py", line 5, in <module>                                            
        from selectmenu import __author__, __version__                        
      File "/tmp/pip-install-z15cw9is/selectmenu_4c361d97c5a1477bbeb17bfbf4f2ae73/selectmenu/__init__.py", line 4, in <module>                              
        from selectmenu.core import SelectMenu                                
      File "/tmp/pip-install-z15cw9is/selectmenu_4c361d97c5a1477bbeb17bfbf4f2ae73/selectmenu/core.py", line 6, in <module>                                  
        from prompt_toolkit.token import Token                                
    ImportError: cannot import name 'Token' from 'prompt_toolkit.token' (/usr/lib/python3/dist-packages/prompt_toolkit/token.py)                            
    ----------------------------------------                                  
WARNING: Discarding https://files.pythonhosted.org/packages/a1/9d/0692d5996b163b8d5eba7b3743b70e9f2da513d818ddde1a4f9573340341/SelectMenu-1.0.0b1.tar.gz#sha256=6da29a48da916b2e794e92c689fb6c264205a9886d41fb35d1aac0533de9ee62 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.                 
ERROR: Could not find a version that satisfies the requirement SelectMenu
ERROR: No matching distribution found for SelectMenu

(With Python 3.9)

**Comment by Chamepp** [comment]
Whats your operating system ?

**Comment by DevJohann** [comment]
> Whats your operating system ?

Im using a Kali Linux VM in Win 10

**Comment by Chamepp** [comment]
Check for your VM permissions on files.
I think the problem is in the windows case and system permissions on files as it seems.

**Comment by Gunbooldre** [comment]
When i do 'python3 main.py' it shows 
Traceback (most recent call last):
  File "C:\Users\User\Desktop\GoogleForms-master\GoogleForms-master\App\main.py", line 4, in <module>
    from sty import fg, bg, ef
ModuleNotFoundError: No module named 'sty'

**Comment by Chamepp** [comment]
use command
pip3 install -r requirements.txt

**Comment by Gunbooldre** [comment]
Yeap, but after i get this kinda message

C:\Users\User\Desktop\GoogleForms-master (1)\GoogleForms-master\App>pip3 install -r requirements.txt
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting string-color
  Using cached string_color-1.2.1-py3-none-any.whl (13 kB)
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-h86w6g_y\\selectmenu_1b29be481fdf435f810a24101a9feed8\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-h86w6g_y\\selectmenu_1b29be481fdf435f810a24101a9feed8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-2em9ep9e'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_1b29be481fdf435f810a24101a9feed8\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_1b29be481fdf435f810a24101a9feed8\setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_1b29be481fdf435f810a24101a9feed8\selectmenu\__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_1b29be481fdf435f810a24101a9feed8\selectmenu\core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ModuleNotFoundError: No module named 'prompt_toolkit'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cd/b9/8078a7f34c5b877e7fa26e5c5c5f62cbc765d44c949dd672a29aef62089a/SelectMenu-1.0.0b2.tar.gz#sha256=9e8623a5ac1a632b5f1e7a96698d62f7e76a4307639e4d7433e8a1a28c263e73 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached SelectMenu-1.0.0b1.tar.gz (2.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-h86w6g_y\\selectmenu_06da8e1517d84a538ba8c9293f932b53\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-h86w6g_y\\selectmenu_06da8e1517d84a538ba8c9293f932b53\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\User\AppData\Local\Temp\pip-pip-egg-info-g44ww_ok'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_06da8e1517d84a538ba8c9293f932b53\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_06da8e1517d84a538ba8c9293f932b53\setup.py", line 5, in <module>
        from selectmenu import __author__, __version__
      File "C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_06da8e1517d84a538ba8c9293f932b53\selectmenu\__init__.py", line 4, in <module>
        from selectmenu.core import SelectMenu
      File "C:\Users\User\AppData\Local\Temp\pip-install-h86w6g_y\selectmenu_06da8e1517d84a538ba8c9293f932b53\selectmenu\core.py", line 6, in <module>
        from prompt_toolkit.token import Token
    ModuleNotFoundError: No module named 'prompt_toolkit'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/9d/0692d5996b163b8d5eba7b3743b70e9f2da513d818ddde1a4f9573340341/SelectMenu-1.0.0b1.tar.gz#sha256=6da29a48da916b2e794e92c689fb6c264205a9886d41fb35d1aac0533de9ee62 (from https://pypi.org/simple/selectmenu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement SelectMenu (from versions: 1.0.0b1, 1.0.0b2)
ERROR: No matching distribution found for SelectMenu

**Comment by Chamepp** [comment]
As it seems you're using Windows.
Check for the file permissions

**Comment by Chamepp** [comment]
The problem is with Select Menu package
Try to install package separately

**Comment by Gunbooldre** [comment]
Yeah, its problem with this pack, but i google it, what wrong with this pack and didt find any info. IDK what to do, to be honest

**Comment by Gunbooldre** [comment]
I also try install it separately, but it doesnt work

**Comment by Gunbooldre** [comment]
What kinda version of python did you use ?

**Comment by Chamepp** [comment]
3.9

**Comment by unxpk** [comment]
is this work for getting google form answer ?

**Comment by Chamepp** [comment]
use **

> pip3 install 'prompt_toolkit==1.0.14'

**
try to install **prompt-toolkit** with the version mentioned (1.0.14)
then try

>  pip3 install SelectMenu
